### ISSUE TITLE
Add actionTakerAddress field to donations created by simulation script

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#320]
`actionTakerAddress` (used in csv) is not supported in simulation script and donations created will not have this field set.
In brief, this field shows who has made the transaction which has created the donation(s). You can see the logic in application core and `scripts/migrations/addActionTakerToDonations.js` script.

The `scripts/migrations/addActionTakerToDonations.js` script has been written before, and doesn't utilize `getTransaction` function in `src/blockchain/lib/web3Helpers.js`. Please use that function in simulation script to get transaction info (every where we have `web3.eth.getTransaction`);

**Comment by mohammadranjbarz** [comment]
I think we have some problems because every donations that simulation script create have txHash not homeTxHash,  so what about direct donations?
should we run simulation script with homeNodeUrl to create direct donations?

And for adding `actionTakerAddress` I think we don't have problem and I saw this function `web3.eth.getTransaction` that you said

**Comment by mohammadranjbarz** [comment]
@GriffGreen  @aminlatifi 

Oh sorry I checked it and I saw it's in the progress, I was wrong I thought it's finished, I'll reopen it.

**Comment by aminlatifi** [comment]
@mohammadranjbarz Is it done?

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
yes it is, now created donations by simulation have this field

**Comment by aminlatifi** [comment]
@mohammadranjbarz Thanks
